### ISSUE TITLE
error code 

### ISSUE THREAD

**Issue by maobuz** [algirdasc/hass-floureon#10]
Dettagli registro (WARNING)
Logger: homeassistant.loader
Source: loader.py:463
First occurred: 2:49:23 (1 occurrences)
Last logged: 2:49:23

You are using a custom integration for floureon which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.

**Comment by algirdasc** [comment]
This is normal. This component is not official. Yet.
