### ISSUE TITLE
read_status error: [Errno -4000] Network timeout

### ISSUE THREAD

**Issue by Gorgue** [algirdasc/hass-floureon#11]
I recently did the integration with a new beok thermostat and it worked correctly, yesterday after updating the home assistant, the integration no longer works, I cannot see the temperature or perform actions. Looking at the log the same error always appears:

`2020-12-15 10:42:05 WARNING (SyncWorker_4) [custom_components.floureon] Thermostat 192.168.0.56 read_status error: [Errno -4000] Network timeout`

**Comment by mauro967** [comment]
It rarely happened now more and more often ...

Logger: custom_components.floureon
Source: custom_components/floureon/__init__.py:70
Integration: floureon (documentation, issues)
First occurred: 18:18:43 (24 occurrences)
Last logged: 20:00:45

Thermostat 192.168.1.20 read_status error: [Errno -4000] Network timeout

**Comment by lello1976** [comment]
HA fails to connect with the beok 002 thermostat.

this is the error

Logger: custom_components.floureon
Source: custom_components/floureon/__init__.py:70 
Integration: floureon (documentation, issues) 
First occurred: 16:29:22 (2 occurrences) 
Last logged: 16:30:22

Thermostat 192.168.1.xxx read_status error: [Errno -4000] Network timeout

someone can help me please

**Comment by algirdasc** [comment]
`[Errno -4000] Network timeout` means connection error - either thermostat is disconnected from wifi or is unreachable by Home Assistant. If problem still exists, reopen this issue.

**Comment by parsonsagain** [comment]
Same:

This error originated from a custom integration.

Logger: custom_components.floureon
Source: custom_components/floureon/__init__.py:70
Integration: floureon (documentation, issues)
First occurred: 18:55:27 (19 occurrences)
Last logged: 19:13:45

Thermostat 192.168.1.12 read_status error: [Errno -4000] Network timeout: No response received within 3s

**Comment by micasitadomotica** [comment]
Hi.
I have the same problem. 
I have checked the IP connectivity from the Raspberry Pi where I have home assistant to the thermostat and it is correct. 

Logger: custom_components.floureon
Source: custom_components/floureon/__init__.py:60
Integration: floureon ([documentation](https://github.com/algirdasc/hass-floureon), [issues](https://github.com/algirdasc/hass-floureon/issues))
First occurred: 23:03:46 (1 occurrences)
Last logged: 23:03:46

Thermostat 192.168.0.117 set_time error: [Errno -4000] Network timeout: No response received within 3s
