### ISSUE TITLE
Multiple devices

### ISSUE THREAD

**Issue by atrunov-89** [algirdasc/hass-floureon#12]
Hi! First of all thank you so much for the integration! It's was not easy to find it for Beok-like devices. Can you explain how is it possible to add multiple devices in the configuration? Thank you!

**Comment by algirdasc** [comment]
Hi, you can add it as follows:

```
- platform: floureon
  name: thermostat1
  host: 192.168.0.10

- platform: floureon
  name: thermostat2
  host: 192.168.0.11

- platform: floureon
  name: thermostat3
  host: 192.168.0.12
```

**Comment by atrunov-89** [comment]
Hi! Ok, clear, thank you!
