### ISSUE TITLE
Sensor settings resets after updating temperature from HA

### ISSUE THREAD

**Issue by DangerD1024** [algirdasc/hass-floureon#13]
On Beok you can select internal sensor (air temperature), external (floor temperature), both external and internal (SEN 2) to avoid overheating floor.
After updating temperature from Home Assistant it resets sensor to 0 on thermostat. Is there any way to prevent that?

Demo
https://youtu.be/pyI3DKjUC6s

**Comment by algirdasc** [comment]
You can use `use_external_temp` to use internal/external temperature sensor. So far there is no option to use both sensors, but this can be doable if you need it.

**Comment by DangerD1024** [comment]
I need that =) where I should update code?)

**Comment by algirdasc** [comment]
Quick workaround would be to change line 105 in climate.py:
`return BROADLINK_SENSOR_EXTERNAL if self._use_external_temp is True else BROADLINK_SENSOR_INTERNAL`
to 
`return BROADLINK_SENSOR_BOTH`

If you're using switch component, switch.py line 90 should be changed in the same way. Let me know how it went for you.

**Comment by DangerD1024** [comment]
I'll try now to modify script, the problem that i need all 3 options as i have 5 thermostats...

**Comment by DangerD1024** [comment]
[floureon.zip](https://github.com/algirdasc/hass-floureon/files/5957551/floureon.zip)
Looks like i did something wrong, i've added use_both_temp to configuration, but now it doesn't show temperature...

**Comment by DangerD1024** [comment]
[floureon.zip](https://github.com/algirdasc/hass-floureon/files/5957614/floureon.zip)
I've added use_both_temp option, works fine, thank you.

**Comment by algirdasc** [comment]
Glad to hear. Good luck!
