### ISSUE TITLE
floureon not found

### ISSUE THREAD

**Issue by pisda** [algirdasc/hass-floureon#17]
Hi,
I have update to Home Assistant OS Version  core-2021.7.0, python 3.9.5 on raspberry 4.
Since I updated the thermostat entity for a beok 313 it doesn't work. The reported error is: Platform error:
Logger: homeassistant.config
Source: config.py:849
First occurred: 8:51:00 (1 occurrences)
Last logged: 8:51:00
climate - Integration 'floureon' not found.
In my climate.yaml i have:
platform: floureon
name: sala
#mac: 24:df:a7:13:bc:9a    #########MAC 
host: 192.168.50.53        #########IP Address
use_external_temp: false

Sorry but I am new to the home assistant system. Thank you.

**Comment by algirdasc** [comment]
Please paste autoformated config, beacuse it looks like the configuration is incorrect.

**Comment by pisda** [comment]
Hi,
Problem solved, I updated the flueron version from the github. With the old version of home assistant it worked but with the new version of HA probably, I think, the "old" version of manifest.json did not work
Thank you.
