### ISSUE TITLE
I don't work

### ISSUE THREAD

**Issue by jaloto74** [algirdasc/hass-floureon#2]
Detalls del registre (WARNING)
Logger: custom_components.floureon
Source: custom_components/floureon/__init__.py:65
Integration: floureon (documentation, issues)
First occurred: 9:26:29 (12 occurrences)
Last logged: 9:37:29

Thermostat 192.16x.xx.xx read_status error: The device is offline

**Comment by xally-pt** [comment]
I have a Baxi Unit using Broadlink and I get this message: Login attempt failed
Login attempt or request with invalid authentication from fe80::ccf:b4b9:2722:a7e5
