### ISSUE TITLE
set_time error: [Errno -4000] Network timeout

### ISSUE THREAD

**Issue by doppiaemme** [algirdasc/hass-floureon#20]
Hi, 

I keep getting this error (I'm on the last HA release)

2021-11-16 18:36:43 ERROR (SyncWorker_6) [custom_components.floureon] Thermostat 192.XX.XX.78 set_time error: [Errno -4000] Network timeout: No response received within 3s

Any idea how to solve it?
Thermostat works fin with the native app.

**Comment by parsonsagain** [comment]
Mine was working but as of 7,3 update has stopped.

**Comment by algirdasc** [comment]
Errno -4000 means that thermostat cannot be reached or did not respond propely. If thermostat was working good before - maybe IP has changed or thermostat is unreachable. If you setting up it first time, might be that your thermostat is not broadlink based and is not supported.
