### ISSUE TITLE
SwitchDevide is deprecated

### ISSUE THREAD

**Issue by RaulVKoNe** [algirdasc/hass-floureon#21]
- Error using the thermostat as a switch

Logger: homeassistant.components.switch
Source: components/switch/__init__.py:130
Integration: Interruptor (documentation, issues)
First occurred: 04:04:00 (1 occurrences)
Last logged: 04:04:00

SwitchDevice is deprecated, modify FloureonSwitch to extend SwitchEntity

Note: Reemplace SwitchDevice to SwitchEntity in
 switch.py, line 23 and 66

**Comment by algirdasc** [comment]
Thank you for info. Fixed.
