### ISSUE TITLE
Floureon integration not appearing in "add integration" after installing through HACS

### ISSUE THREAD

**Issue by taumic** [algirdasc/hass-floureon#24]
Not sure if its an issue but it seems that I cannot use the component as It is not showing up in integrations menu.
HACS installs repository correctly.

Maybe I am installing it incorrectly?
Thanks for help!

**Comment by jaloto74** [comment]
A few days ago I had problems and it was derived from the application.  I reinstalled again and it works fine.  Try reinstalling the application if it can't be that you have migrated the ip to a different ip

**Comment by taumic** [comment]
Do you mean reinstall HACS?

**Comment by jaloto74** [comment]
Beok (floureon) APP

**Comment by algirdasc** [comment]
> Not sure if its an issue but it seems that I cannot use the component as It is not showing up in integrations menu. HACS installs repository correctly.
> 
> Maybe I am installing it incorrectly? Thanks for help!

There is no possibility to add integration using HA GUI. You need to configure climate / switch component in config files.
