### ISSUE TITLE
Integration does not work with de last update

### ISSUE THREAD

**Issue by sergiocarba** [algirdasc/hass-floureon#26]
Hello,

After the last update the integration does not work. The error is: 

Invalid config for [climate.floureon]: [mac] is an invalid option for [climate.floureon]. Check: climate.floureon->mac. (See ?, line ?). 

Do someone have the same problem?

Thank you very much.

**Comment by algirdasc** [comment]
Hello. MAC parameter was deprecated some time ago. After last update, this parameter was removed, you can safely remove it from your config (`host:` will be enough).

**Comment by sergiocarba** [comment]
Hello, thank you. Now it is working fine. The problem is solved.

Best regards.
