### ISSUE TITLE
Floureon stops to work after update to last version - using HA 2022.08.02

### ISSUE THREAD

**Issue by robi59italy** [algirdasc/hass-floureon#27]
getting this message:
Invalid config for [climate.floureon]: [mac] is an invalid option for [climate.floureon]. Check: climate.floureon->mac. (See /config/configuration.yaml, line 28). Please check the docs at https://github.com/algirdasc/hass-floureon
Invalid config for [climate.floureon]: [mac] is an invalid option for [climate.floureon]. Check: climate.floureon->mac. (See /config/configuration.yaml, line 33). Please check the docs at https://github.com/algirdasc/hass-floureon

here my configuration.yaml

climate:
  - platform: floureon
    name: Soggiorno_termostato
    mac: 24:DF:A7:13:AA:E1
    host: 192.168.1.6
    use_external_temp: false
  - platform: floureon
    name: Caldaia_ufficio
    mac: A0:43:B0:D4:86:5C
    host: 192.168.1.14
    use_external_temp: false

ip and mac confirmed by scanning my network

**Comment by jannylund** [comment]
@robi59italy please see answer on this ticket. https://github.com/algirdasc/hass-floureon/issues/26

**Comment by robi59italy** [comment]
thanks for fast support. Working ok!
I'm strongly suggesting to adjust the main page removing MAC from the "example"...

**Comment by algirdasc** [comment]
Thanks for the note. `mac` was removed from example.
