### ISSUE TITLE
Latest update breaks component

### ISSUE THREAD

**Issue by privatesam** [algirdasc/hass-floureon#29]
I saw the update to this component in my HACS so upgraded but it broke all the floureon thermostats in Home Assistant.  Kept getting:

```No module named 'homeassisant.util.unit_conversion'```

in the logs.  I reverted and its ok now.  Not sure what the issue was - might have a dig around later if I get the chance.

**Comment by algirdasc** [comment]
What HA version do you use?

**Comment by privatesam** [comment]
Home Assistant 2022.9.7 Frontend 20220907.2 - latest

**Comment by algirdasc** [comment]
Do you have posibility to upgrade to 2022.10?

**Comment by msanya** [comment]
Hi! I have the same error.  - No module named 'homeassisant.util.unit_conversion'
Home Assistant 2022.9.4
Supervisor 2022.10.0
Operating System 9.0
Kezelőfelület 20220907.2 - latest

I can't upgrade HA now :-(

**Comment by algirdasc** [comment]
> Hi! I have the same error. - No module named 'homeassisant.util.unit_conversion' Home Assistant 2022.9.4 Supervisor 2022.10.0 Operating System 9.0 Frontend 20220907.2 - latest
> 
> I can't upgrade HA now :-(

I've added backward compatability with older HA versions, could you confirm that it is working now?

**Comment by ccavallin65** [comment]
I've updated and now it's working.

**Comment by algirdasc** [comment]
Good to hear! I'm closing this issue.
