### ISSUE TITLE
Entity not working after upgrading home assistant to 115.1

### ISSUE THREAD

**Issue by petikeje** [algirdasc/hass-floureon#3]
Hi,
There were a lot of modification in home assistant 115 on broadlink component. After the upgrade home assistant upgrade the floureon component not orking any more.
Could you please check and fix it.
THX and BR:
 P!

**Comment by algirdasc** [comment]
Hello, could you please try to update to newest version? I've modified manifest, which should be enough to start working again.

**Comment by petikeje** [comment]
It works. Best!
THX!
