### ISSUE TITLE
Setting thermostat to 'auto' using 'Climate: Set HVAC mode' = incorrect settings.

### ISSUE THREAD

**Issue by RobN185** [algirdasc/hass-floureon#35]
All works well with the BEOK thermostat except for the following issue.
When the thermostat is set to 'auto' using 'Climate: Set HVAC mode', the Thermostat Time Period and Temperature are both set incorrectly.
eg. 
Thermostat time periods set as follows...
Period 1 = 8:30am    20.0 deg
Period 2 = 10:00am    21.0 deg
Period 3 = 12:00am    19.0 deg
Period 4 = 14:00am    20.0 deg
Period 5 = 17:00am    23.0 deg
Period 6 = 23:00am    15.0 deg

If current time is 10:30am then setting the Climate: Set HVAC mode' to 'auto' should result in 
the Time Period 2 and a temperature of 21.0 deg.  
BUT...
it actually sets the **Time Period to 1** and the temperature to **16.0** deg !

The Devoloper State tool showed the following states (before Climate : Set HVAC mode )...

hvac_modes: auto, heat, off 
min_temp: 5 
max_temp: 40 
preset_modes: none, away 
current_temperature: 21.5 
temperature: 21 
hvac_action: 
idle preset_mode: none 
away_set_point: 7 
manual_set_point: 21 
external_temp: 0 
room_temp: 21.5 
loop_mode: 2 
friendly_name: lounge 
supported_features: 17

**EDIT 3/2/2024**
I think that I may have found the issue.
The official BEOK app is showing that schedule "**1234567**" is active, and I have selected loop "**2**" in the add-on settings so both should be matched.
However, when I change the hvac_mode to "**auto**" the temperature for the thermostat is selected from "**12345, 67**" schedule and not the "**1234567**" schedule that was set in both the app and the add-in. 

Hope this helps !

**Comment by duedipicche** [comment]
I have the same problem, when I go from auto to off or from auto to heat, when I go back to auto the thermostat always goes to period 1.
To go back to the right period I have to physically act on the thermostat by switching first to manual and then to automatic.
The Beok thermostat is on "123456,7" and the climate of HA schedule=1
