### ISSUE TITLE
Deprecation of TEMP_CELSIUS

### ISSUE THREAD

**Issue by litinoveweedle** [algirdasc/hass-floureon#39]
HA show warning about deprecated constant:

TEMP_CELSIUS was used from floureon, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please report it to the author of the 'floureon' custom integration.

PR #38  fix this in the simple manner of replacing TEMP_CELSIUS imported constant to UnitOfTemperature.CELSIUS as suggested.

**Comment by litinoveweedle** [comment]
I missed one more deprecation causing this warnings:

Entity None (<class 'custom_components.floureon.climate.FloureonClimate'>) does not set ClimateEntityFeature.TURN_OFF but implements the turn_off method. Please create a bug report at https://github.com/algirdasc/hass-floureon/issues
Entity None (<class 'custom_components.floureon.climate.FloureonClimate'>) does not set ClimateEntityFeature.TURN_ON but implements the turn_on method. Please create a bug report at https://github.com/algirdasc/hass-floureon/issues
Entity None (<class 'custom_components.floureon.climate.FloureonClimate'>) implements HVACMode(s): auto, heat, off and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/algirdasc/hass-floureon/issues

It is now included in PR #40 together with #39

**Comment by algirdasc** [comment]
Thank you for your fixes 👍
