### ISSUE TITLE
Temperature

### ISSUE THREAD

**Issue by duedipicche** [algirdasc/hass-floureon#41]
Add entity sensor.temperature if possible.

**Comment by algirdasc** [comment]
You can use floureon thermostat as a switch and use template climate integration to use your desired temperature sensor.

**Comment by duedipicche** [comment]
I wanted to know if it was possible to read the room temperature of the thermostat, I do not want to set the temperature, but read the temperature shown by the internal sensor of the thermostat.
Thanks

**Comment by duedipicche** [comment]
Thank you
close issue
