### ISSUE TITLE
Max temperature issue after upgrade to HA 24.10

### ISSUE THREAD

**Issue by agnus777** [algirdasc/hass-floureon#43]
I installed over 3 years ago a Floureon themrostat in a solar puffer to monitor tempratures.

I added the below to the climate.yaml

  - platform: floureon
    unique_id: Temp_Caldaia/Solare
    name: Caldaia/Solare 
    host: 192.168.1.86
    use_external_temp: true
    precision: 0.5

One year ago I added an electiral heater  to the puffer to help the system during winter and I added the below to configuration.yaml in order to have capabilities to set max temperature before turn it off.

switch:
  platform: floureon
  unique_id: switch.Caldaia_Solare
  name: Caldaia/Solare_switch 
  host: 192.168.1.86
  use_external_temp: true
  turn_off_mode: turn_off
  turn_on_mode: 52

Yesterday after upgrading to HA 24.10, the max temperature is set to 35° and I cannot increase it.

![image](https://github.com/user-attachments/assets/d0500861-24b0-4f5c-9f5f-1c526c2c699b)

Is there something that I can do it to solve it?

thanks in advance.

**Comment by algirdasc** [comment]
Home Assistant has max temp of 35, but component can set any value you'll define - can you check what thermostat screen display?

**Comment by agnus777** [comment]
Before that update, HA overwrite the me temperature. But, as you wrote, I defined manually directly on the thermostat to adjust to desire temperature.
I solved but it's a strange behaviour of integration...
