### ISSUE TITLE
Beok BOT313 reset GMT time.

### ISSUE THREAD

**Issue by duedipicche** [algirdasc/hass-floureon#44]
I don't know if it depends on the integration, but every time I make a restart of homeassistant the integration resets the time on my beok at the GMT time.
The computer where  HomeAssistant run  is set on GMT +1 
If I disable the integration and restart homeassistant, the time on my beok remains the exact one.
It is very strange, but it happens.

**Comment by algirdasc** [comment]
Yes, when HA loads the component, it sets the time on the thermostat based on the time in HA.

**Comment by duedipicche** [comment]
the time on HA is set to GMT+1, as in the picture, but the thermostat is set to GMT on every reboot.

![Immagine 2024-10-09 201704](https://github.com/user-attachments/assets/aee6799b-befc-4886-84d0-7c10b543002d)

**Comment by algirdasc** [comment]
Are you sure your OS, where HA is running is set to correct date?

**Comment by duedipicche** [comment]
Sorry.
Correct timezone in HA  docker installation.
