### ISSUE TITLE
mac option is deprecated. It will be removed in future releases

### ISSUE THREAD

**Issue by Asom-Velz** [algirdasc/hass-floureon#9]
Hi

After the last update to Home Assistant 0.117.5 I receive the following error:

Logger: custom_components.floureon.climate
Source: custom_components/floureon/climate.py:76 
Integration: floureon (documentation, issues) 
First occurred: 15:01:29 (1 occurrences) 
Last logged: 15:01:29

mac option is deprecated. It will be removed in future releases. Please modify your config accordingly.

**Comment by algirdasc** [comment]
You should modify your config file and remove `mac: XX:XX:XXX....` option.
